# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  catalogdb:
    image: postgres
  # adminer:
  #   image: adminer
  # catalogapi:
  #   image: gilmartd/catalog-api
volumes:
  postgres_catalog:
